#=========================== begin_copyright_notice ============================
#
# INTEL CONFIDENTIAL
#
# Copyright 2020-2021 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit this
# software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.
#
#============================ end_copyright_notice =============================

name: Notify
on:
  status:
  pull_request_review:

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Get branch name if status changed
        if: github.event_name == 'status'
        run: >
          echo "os_branch=${{ github.event.branches[0].name }}" >> $GITHUB_ENV
      - name: Get branch name if pr review state changed
        if: github.event_name == 'pull_request_review'
        run: >
          echo "os_branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
      - name: Notify
        run: ${{ secrets.NOTIFY }}
